### PR TITLE
Check for setup failures

### LINKED ISSUE #120: pytest flaky interaction causing fixture exceptions to be ignored
Somewhat related to [this issue](https://github.com/pytest-dev/pytest/issues/1480) which was supposedly resolved in Flaky 3.1.1 

In the example below, something in flaky is causing the exception that is thrown inside the fixture not to be reported anymore. 
```
import pytest
import flaky

@pytest.fixture
def failing_fixture():
    raise Exception("Woops")

@flaky.flaky()
@pytest.mark.usefixtures('failing_fixture')
class TestCases:
    def test_fixture_fail(self):
        pass

    def test_always_pass(self):
        assert True

    def test_always_fail(self):
        assert False
```
The test results show that 3 tests were gathered but none were executed (which is true) but leaves no trace to the exception in the fixture. 
```

platform linux -- Python 3.5.1, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/thou/mine/python_scribbles, inifile: 
plugins: flaky-3.3.0
collected 3 items 

my_pytest.py 
===Flaky Test Report===


===End Flaky Test Report===

 no tests ran in 0.02 seconds
```

If we remove the flaky decorator from the test class, the error is reported normally.

### PR DESCRIPTION
**Pull request by nmalaguti**
Fixes #120, #117, #124, #114

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @nmalaguti, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by nmalaguti** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @nmalaguti has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by Jeff-Meadows** [comment]
This change does legitimately cause the tox tests to fail with xdist. I'm not totally sure why. This looks good to merge once that's resolved.

**Comment by nmalaguti** [comment]
So I couldn't get it working with xdist to retry when there was a setup failure, but not retrying on setup failures worked to make sure setup failures don't silently pass.

**Comment by nmalaguti** [comment]
@Jeff-Meadows things should be good now if you want to take a look.

**Comment by Jeff-Meadows** [comment]
@nmalaguti I feel like I used to be able to merge things even with failing Travis tests; that appears to no longer be the case. I'm ready to merge this as soon as I can. I fixed a bunch of the Travis tests in another commit, but one pylint error remains - could you add a pylint directive to your test code to ignore the unused argument?

**Comment by nmalaguti** [comment]
@Jeff-Meadows updated and green!

**Pull request merged**
