### PR TITLE
Remove nose support

### PR DESCRIPTION
**Pull request by stratakis**
The nose test runner hasn't been actively developed since 2016.

Co-authored by mcepl@suse.com

### CODE REVIEW

**Comment by stratakis** [comment]
Resolves #181 #171

**Comment by Jeff-Meadows** [comment]
Looks like the repo needed to be migrated to travis-ci.com instead of travis-ci.org, so I'm going to try to close and reopen the PR to trigger the CI build.

**Comment by stratakis** [comment]
Ping. Would it be possible to move this forward?

**Comment by cclauss** [comment]
Please rebase.  Tox is now running again under GitHub Actions.
* https://github.com/box/flaky/actions

**Comment by stratakis** [comment]
Rebased.

**Review by cclauss — APPROVED** [review]

**Pull request merged**
