### PR TITLE
Update flaky_pytest_plugin.py

### PR DESCRIPTION
**Pull request by mikehab**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @mikehab, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by jmoldow** [comment]
This looks good to me. @Jeff-Meadows ?

@mikehab , please sign the CLA so that we may merge this.

**Comment by Jeff-Meadows** [comment]
:+1: waiting on "CLA signed"

**Comment by mikehab** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @mikehab has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by jmoldow** [comment]
Merged. Thanks for the pull request!

**Pull request merged**
