### PR TITLE
Support multiprocessing

### PR DESCRIPTION
**Pull request by benpatterson**
Hi @Jeff-Meadows 

I wanted your feedback, if possible, while I continue to work on this. At this point I need to adjust pytest tests (and I admit I have more experience with nose than with pytest. I'd welcome the assistance but your review is the most valuable!)

If you would rather review when I am done with the work, that is also fine. I can tag you when that time comes, too.

But the reason I'm pinging you now is more about the important concepts, which are as follows:
* This leverages the multiprocessing Manager. This is how I've seen multiprocessing implemented according to the [documentation](https://docs.python.org/2/library/multiprocessing.html), as well as the [xunitmp nose plugin](https://github.com/Ignas/nose_xunitmp).
* Because the manager runs at such a high level, it is essentially a global process, which also matches the above implementation patterns
* Because it is a global process, it is difficult (if not impossible) to mock. So the tests now instead use the global process, clearing its contents at the beginning of each test run. This is the pattern I would expect to implement in the pytest unit tests when I can get to them. 

Thanks for any feedback!

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @benpatterson, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by benpatterson** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @benpatterson has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by Jeff-Meadows** [comment]
Hey @benpatterson pytest is already working with the xdist plugin (see #35 fixed by #38). 

If I were tackling this, I'd probably subclass the MP list to give it a stream-like interface, and use it only in the nose plugin. That way, you won't need to touch the pytest plugin or the base class.

Does that sound like a good direction?

**Comment by benpatterson** [comment]
Ah thanks for the feedback, @Jeff-Meadows, let me go in that direction and see what I can do.

**Comment by benpatterson** [comment]
Closing in favor of #67

**Pull request closed without merging**
